# Generated by Django 2.2 on 2021-01-01 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtentionUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(default='', max_length=120)),
                ('country', models.CharField(choices=[('', 'Select'), ('Argentina', 'Argentina'), ('Australia', 'Australia'), ('Austria', 'Austria'), ('Belgium', 'Belgium'), ('Brazil', 'Brazil'), ('Bulgaria', 'Bulgaria'), ('Canada', 'Canada'), ('China', 'China'), ('Colombia', 'Colombia'), ('Czech Republic', 'Czech Republic'), ('Egypt', 'Egypt'), ('France', 'France'), ('Germany', 'Germany'), ('Greece', 'Greece'), ('Hong Kong', 'Hong Kong'), ('Hungary', 'Hungary'), ('India', 'India'), ('Indonesia', 'Indonesia'), ('Ireland', 'Ireland'), ('Israel', 'Israel'), ('Italy', 'Italy'), ('Japan', 'Japan'), ('Latvia', 'Latvia'), ('Lithuania', 'Lithuania'), ('Malaysia', 'Malaysia'), ('Mexico', 'Mexico'), ('Morocco', 'Morocco'), ('Netherlands', 'Netherlands'), ('New Zealand', 'New Zealand'), ('Nigeria', 'Nigeria'), ('Norway', 'Norway'), ('Philippines', 'Philippines'), ('Poland', 'Poland'), ('Portugal', 'Portugal'), ('Romania', 'Hungary'), ('Saudi Arabia', 'Saudi Arabia'), ('Serbia', 'Serbia'), ('Singapore', 'Singapore'), ('Slovakia', 'Slovakia'), ('Slovenia', 'Slovenia'), ('South Africa', 'South Africa'), ('South Korea', 'South Korea'), ('Sweden', 'Sweden'), ('Switzerland', 'Switzerland'), ('Taiwan', 'Taiwan'), ('Thailand', 'Thailand'), ('Turkey', 'Turkey'), ('UAE', 'UAE'), ('Ukraine', 'Ukraine'), ('United Kingdom', 'United Kingdom'), ('United States', 'United States'), ('Venuzuela', 'Venuzuela')], default='', max_length=70)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
