# Generated by Django 2.2 on 2021-01-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extentionuser',
            name='country',
            field=models.CharField(choices=[('', 'Select'), ('ar', 'Argentina'), ('au', 'Australia'), ('at', 'Austria'), ('be', 'Belgium'), ('br', 'Brazil'), ('bg', 'Bulgaria'), ('ca', 'Canada'), ('cn', 'China'), ('co', 'Colombia'), ('cz', 'Czech Republic'), ('eg', 'Egypt'), ('fr', 'France'), ('de', 'Germany'), ('gr', 'Greece'), ('hk', 'Hong Kong'), ('hu', 'Hungary'), ('in', 'India'), ('id', 'Indonesia'), ('Ie', 'Ireland'), ('il', 'Israel'), ('it', 'Italy'), ('jp', 'Japan'), ('lv', 'Latvia'), ('lt', 'Lithuania'), ('my', 'Malaysia'), ('mx', 'Mexico'), ('ma', 'Morocco'), ('nl', 'Netherlands'), ('nz', 'New Zealand'), ('ng', 'Nigeria'), ('no', 'Norway'), ('ph', 'Philippines'), ('pl', 'Poland'), ('pt', 'Portugal'), ('ro', 'Hungary'), ('sa', 'Saudi Arabia'), ('rs', 'Serbia'), ('sg', 'Singapore'), ('sk', 'Slovakia'), ('si', 'Slovenia'), ('za', 'South Africa'), ('kr', 'South Korea'), ('se', 'Sweden'), ('ch', 'Switzerland'), ('tw', 'Taiwan'), ('th', 'Thailand'), ('tr', 'Turkey'), ('ae', 'UAE'), ('ua', 'Ukraine'), ('gb', 'United Kingdom'), ('us', 'United States'), ('ve', 'Venuzuela')], default='', max_length=70),
        ),
    ]
