# Generated by Django 2.2 on 2021-01-03 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20210103_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('country', models.CharField(default='', max_length=70, null=True)),
                ('url', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('img', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('newDate', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('category', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('share_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
