# Generated by Django 2.2 on 2021-01-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='newsAuthor',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
    ]
